name: Nightly Packaging

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  Get_Version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get version
        id: version
        run: |
          VERSION=$(cat VERSION)
          GIT_SHA=$(git rev-parse --short HEAD)
          if [[ "$VERSION" = *-dev ]]; then
            VERSION="${VERSION}+${GIT_SHA}"
          fi
          echo "value=${VERSION}" >> "$GITHUB_OUTPUT"

  Container_Packages:
    name: Container-based packages
    needs: Get_Version
    uses: ./.github/workflows/packages.yml
    with:
      version: ${{ needs.Get_Version.outputs.version }}
