name: Run Valkey tests with luajit

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Update submodule
        run: git submodule update --init --recursive

      - name: Get deps
        run: sudo apt-get install pkg-config tcl8.6 tclx cmake libssl-dev

      - name: Build
        run: ./build.sh --with-tests

      - name: Run tests
        run: ./tests/run-valkey-tests.sh --skiptest "Process title set as expected" --verbose --dump-logs
